spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.url}:${db.port}/${db.schema}
    username: ${db.username}
    password: ${db.password}

  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_insert: true
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          discord:
            clientId: ${discord.client}
            clientSecret: ${discord.secret}
            scope:
              - identify
            redirectUri: "http://localhost:3000/api/v1/user/auth"
            authorizationGrantType: authorization_code
            clientName: discord
            clientAuthenticationMethod: POST
        provider:
          discord:
            authorizationUri: https://discord.com/oauth2/authorize
            tokenUri: https://discord.com/api/oauth2/token
            userInfoUri: https://discord.com/api/v8/users/@me
            userNameAttribute: username